"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "en.json",
    "translation": "%locale%.json",
    "languages_mapping": {
      "locale": {
        "af": "af",
        "am": "am",
        "ar": "ar",
        "be": "be",
        "bg": "bg",
        "bn": "bn",
        "ca": "ca",
        "cs": "cs",
        "da": "da",
        "de": "de",
        "el": "el",
        "eo": "eo",
        "es-ES": "es",
        "eu": "eu",
        "fa": "fa",
        "fi": "fi",
        "fr": "fr",
        "gl": "gl",
        "he": "he",
        "hi": "hi",
        "hu": "hu",
        "id": "id",
        "it": "it",
        "ja": "ja",
        "ko": "ko",
        "lt": "lt",
        "lv": "lv",
        "ml-IN": "ml",
        "ms": "ms",
        "nl": "nl",
        "nn-NO": "nn",
        "no": "no",
        "oc": "oc",
        "pl": "pl",
        "pt-PT": "pt",
        "pt-BR": "pt-BR",
        "ro": "ro",
        "ru": "ru",
        "se": "se",
        "sk": "sk",
        "sq": "sq",
        "sr": "sr",
        "ta": "ta",
        "te": "te",
        "th": "th",
        "tr": "tr",
        "uk": "uk",
        "ur-IN": "ur",
        "uz": "uz",
        "vi": "vi",
        "zh-CN": "zh",
        "zh-TW": "zh-TW",
      }
    }
  }
]
